#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Aug 31 13:14:43 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MyDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyDialog.__init__
		kwds["style"] = wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.label_1 = wx.StaticText(self, -1, "Orden")
		self.combo_box_1 = wx.ComboBox(self, -1, choices=["1", "2", "3", "4", "5", "6", "7", "8"], style=wx.CB_DROPDOWN)

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_TEXT_ENTER, self.enter, self.combo_box_1)
		self.Bind(wx.EVT_COMBOBOX, self.selection, self.combo_box_1)
		# end wxGlade




	def __set_properties(self):
		# begin wxGlade: MyDialog.__set_properties
		self.SetTitle(u"Selección")
		self.combo_box_1.SetSelection(0)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MyDialog.__do_layout
		grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
		grid_sizer_1.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
		grid_sizer_1.Add(self.combo_box_1, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
		self.SetSizer(grid_sizer_1)
		grid_sizer_1.Fit(self)
		self.Layout()
		# end wxGlade


	def accept(self):
		out=wx.ID_OK
		self.value = self.combo_box_1.GetValue()
		self.EndModal(out)


	def selection(self, event): # wxGlade: MyDialog.<event_handler>
		self.accept()		
		event.Skip()

	def enter(self, event): # wxGlade: MyDialog.<event_handler>
		self.accept()		
		event.Skip()

# end of class MyDialog


class MyApp(wx.App):
	def OnInit(self):
		wx.InitAllImageHandlers()
		dialog_1 = MyDialog(None, -1, "")

		if dialog_1.ShowModal()==wx.ID_OK:
			order = dialog_1.value
			print order
			
		dialog_1.Destroy()	
			
		self.SetTopWindow(dialog_1)
		dialog_1.Show()

		return 1

# end of class MyApp

if __name__ == "__main__":
	app = MyApp(0)
	app.MainLoop()
	
	
